name: Build images

on:
  push:
    branches: [ master ]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Build image
        uses: docker/setup-buildx-action@v1
        run: |
          docker buildx build --platform=linux/arm,linux/arm64,linux/amd64 --load -t graphiteapp/graphite-statsd:master .
      - name: Run Snyk to check Docker image for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
          image: temporary
          args: --file=Dockerfile --platform=linux/arm,linux/arm64,linux/amd64 --project-name=graphite-project/docker-graphite-statsd
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      # Use the build cache and push the imagee
      - name: Push image to Docker Hub
        run: |
          docker buildx build --platform=linux/arm,linux/arm64,linux/amd64 --push -t graphiteapp/graphite-statsd:master .